import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import record from '../data/bugs.json'
import Link from 'next/link'
import { useState, useEffect } from 'react'


 var random = Math.floor(Math.random() * record.length);
 var randonObject = record[random];
  var randomNumber = random;
  
  
export default function Home() {
    // useEffect(() => { 
    //     console.log("hi");
    //     var random = Math.floor(Math.random() * record.length);
    //     var randonObject = record[random];
    //     var randomNumber = random;
    
    // }, [])
  console.log(record);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta http-equiv='cache-control' content='no-cache'></meta>
        <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <div>
          {
            record.map((rec, index) => {
              if (index === (randomNumber)){
              return(

                <div className={styles.bugs}>
                <Image className={styles.bugpic} src={rec['Icon Image']} alt={rec} width={100} height={100}/>
                <div>{rec.Name}</div>
                <div className={styles.desc}>{rec.Description}</div>
                </div>
                
                )
              }
            })

          }
        </div>
        <button>
                  <Link href="/">I CHANGE MY MIND</Link>
                  </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


